In [1]:
import numpy as np, pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm


In [106]:
trainFile=pd.read_csv('../input/stance-detection/train_merged.csv',encoding='latin-1')
testFile=pd.read_csv('../input/stance-detection/test_merged.csv', encoding='latin-1')

In [210]:
testFile2=pd.read_excel('../input/gossicop-fake/gossicop_fake_ALL_ST.xlsx', encoding='latin-1')

In [211]:
testFile2.head()

Claim  ...   Stance
6       0  ...        0
14      0  ...        0
17      0  ...        0
18      0  ...        1
20      0  ...        0

[5 rows x 5 columns]

In [212]:
#trainFile.head()

In [213]:
#testFile=pd.read_csv('../input/stance-detection/test_merged.csv', encoding='latin-1')

In [214]:
#trainFile=pd.read_csv('../input/mine-stance-test/gossicop_real0.xlsx',encoding='latin-1')


In [215]:
#df = pd.DataFrame(pd.read_excel('../input/mine-stance-test/gossicop_real0.xlsx',encoding='latin-1'))

In [216]:
#testFile_=pd.read_csv('../input/stance-detection/test_merged.csv', encoding='latin-1')

In [217]:
testFile

Body ID    ...         Stance
0            1    ...      unrelated
1            1    ...          agree
2            1    ...      unrelated
3            1    ...      unrelated
4            1    ...      unrelated
5            1    ...      unrelated
6            1    ...      unrelated
7            1    ...      unrelated
8            1    ...      unrelated
9            1    ...      unrelated
10           1    ...      unrelated
11           1    ...      unrelated
12           1    ...      unrelated
13           1    ...      unrelated
14           1    ...      unrelated
15           1    ...      unrelated
16           1    ...      unrelated
17           1    ...      unrelated
18           1    ...      unrelated
19           2    ...      unrelated
20           2    ...      unrelated
21           2    ...      unrelated
22           2    ...      unrelated
23           2    ...      unrelated
24           2    ...      unrelated
25           2    ...      unrelated
26           2    ...      unrelated
27           2    ...      unrelated
28           2    ...      unrelated
29           2    ...      unrelated
...        ...    ...            ...
25383     2582    ...       disagree
25384     2582    ...       disagree
25385     2582    ...          agree
25386     2582    ...       disagree
25387     2582    ...       disagree
25388     2582    ...          agree
25389     2583    ...        discuss
25390     2583    ...        discuss
25391     2583    ...        discuss
25392     2583    ...        discuss
25393     2583    ...        discuss
25394     2583    ...        discuss
25395     2584    ...          agree
25396     2584    ...          agree
25397     2584    ...       disagree
25398     2584    ...          agree
25399     2584    ...          agree
25400     2584    ...       disagree
25401     2585    ...          agree
25402     2585    ...          agree
25403     2585    ...       disagree
25404     2585    ...          agree
25405     2585    ...          agree
25406     2585    ...       disagree
25407     2586    ...       disagree
25408     2586    ...       disagree
25409     2586    ...          agree
25410     2586    ...       disagree
25411     2586    ...       disagree
25412     2586    ...          agree

[25413 rows x 4 columns]

In [218]:
totaldata= trainFile['articleBody'].tolist() + trainFile['Headline'].tolist()+testFile['articleBody'].tolist()+testFile['Headline'].tolist() + testFile2['Title'].tolist()+testFile2['Tweet'].tolist()

In [219]:
totaldata[0]

'A small meteorite crashed into a wooded area in Nicaragua\'s capital of Managua overnight, the government said Sunday. Residents reported hearing a mysterious boom that left a 16-foot deep crater near the city\'s airport, the Associated Press reports. \r\n\r\nGovernment spokeswoman Rosario Murillo said a committee formed by the government to study the event determined it was a "relatively small" meteorite that "appears to have come off an asteroid that was passing close to Earth." House-sized asteroid 2014 RC, which measured 60 feet in diameter, skimmed the Earth this weekend, ABC News reports. \r\nMurillo said Nicaragua will ask international experts to help local scientists in understanding what happened.\r\n\r\nThe crater left by the meteorite had a radius of 39 feet and a depth of 16 feet,  said Humberto Saballos, a volcanologist with the Nicaraguan Institute of Territorial Studies who was on the committee. He said it is still not clear if the meteorite disintegrated or was buried

In [220]:
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=80, stop_words='english')

In [262]:
tfidf_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=80,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='\\w{1,}', tokenizer=None,
                use_idf=True, vocabulary=None)

In [221]:
tfidf_vect.fit(totaldata)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=80,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='\\w{1,}', tokenizer=None,
                use_idf=True, vocabulary=None)

In [222]:
#testFile['Headline']

In [223]:
train_head_vec= tfidf_vect.transform(trainFile['Headline'])
train_body_vec= tfidf_vect.transform(trainFile['articleBody'])
#test_head_vec= tfidf_vect.transform(testFile['Headline'])
#test_body_vec= tfidf_vect.transform(testFile['articleBody'])
test_head_vec2= tfidf_vect.transform(testFile2['Title'])
test_body_vec2= tfidf_vect.transform(testFile2['Tweet'])

In [224]:
# run and tested
import os
import re
import nltk
import numpy as np
from sklearn import feature_extraction
from tqdm import tqdm


_wnl = nltk.WordNetLemmatizer()


def normalize_word(w):
    return _wnl.lemmatize(w).lower()


def get_tokenized_lemmas(s):
    return [normalize_word(t) for t in nltk.word_tokenize(s)]


def clean(s):
    # Cleans a string: Lowercasing, trimming, removing non-alphanumeric

    return " ".join(re.findall(r'\w+', s, flags=re.UNICODE)).lower()


def remove_stopwords(l):
    # Removes stopwords from a list of tokens
    return [w for w in l if w not in feature_extraction.text.ENGLISH_STOP_WORDS]


def gen_or_load_feats(feat_fn, headlines, bodies, feature_file):
    if not os.path.isfile(feature_file):
        feats = feat_fn(headlines, bodies)
        np.save(feature_file, feats)

    return np.load(feature_file)




def word_overlap_features(features, headline, body):
    # common word/ total word
    clean_headline = clean(headline)
    clean_body = clean(body)
    clean_headline = get_tokenized_lemmas(clean_headline)
    clean_body = get_tokenized_lemmas(clean_body)
    feature = len(set(clean_headline).intersection(clean_body)) / float(len(set(clean_headline).union(clean_body)))
    features.append(feature)
    return features




def ngrams(input, n):
    input = input.split(' ')
    output = []
    for i in range(len(input) - n + 1):
        output.append(input[i:i + n])
    return output


def chargrams(input, n):
    output = []
    for i in range(len(input) - n + 1):
        output.append(input[i:i + n])
    return output


def append_chargrams(features, text_headline, text_body, size):
    grams = [' '.join(x) for x in chargrams(" ".join(remove_stopwords(text_headline.split())), size)]
    grams_hits = 0
    grams_early_hits = 0
    grams_first_hits = 0
    for gram in grams:
        if gram in text_body:
            grams_hits += 1
        if gram in text_body[:255]:
            grams_early_hits += 1
        if gram in text_body[:100]:
            grams_first_hits += 1
    features.append(grams_hits)
    features.append(grams_early_hits)
    features.append(grams_first_hits)
    return features


def append_ngrams(features, text_headline, text_body, size):
    grams = [' '.join(x) for x in ngrams(text_headline, size)]
    grams_hits = 0
    grams_early_hits = 0
    for gram in grams:
        if gram in text_body:
            grams_hits += 1
        if gram in text_body[:255]:
            grams_early_hits += 1
    features.append(grams_hits)
    features.append(grams_early_hits)
    return features


def hand_features(headlines, bodies):
    def binary_co_occurence(headline, body):
        # Count how many times a token in the title
        # appears in the body text.
        bin_count = 0
        bin_count_early = 0
        for headline_token in clean(headline).split(" "):
            if headline_token in clean(body):
                bin_count += 1
            if headline_token in clean(body)[:255]:
                bin_count_early += 1
        return [bin_count, bin_count_early]

    def binary_co_occurence_stops(headline, body):
        # Count how many times a token in the title
        # appears in the body text. Stopwords in the title
        # are ignored.
        bin_count = 0
        bin_count_early = 0
        for headline_token in remove_stopwords(clean(headline).split(" ")):
            if headline_token in clean(body):
                bin_count += 1
                bin_count_early += 1
        return [bin_count, bin_count_early]

    def count_grams(headline, body):
        # Count how many times an n-gram of the title
        # appears in the entire body, and intro paragraph

        clean_body = clean(body)
        clean_headline = clean(headline)
        features = []
        features = append_chargrams(features, clean_headline, clean_body, 2)
        features = append_chargrams(features, clean_headline, clean_body, 8)
        features = append_chargrams(features, clean_headline, clean_body, 4)
        features = append_chargrams(features, clean_headline, clean_body, 16)
        features = append_ngrams(features, clean_headline, clean_body, 2)
        features = append_ngrams(features, clean_headline, clean_body, 3)
        features = append_ngrams(features, clean_headline, clean_body, 4)
        features = append_ngrams(features, clean_headline, clean_body, 5)
        features = append_ngrams(features, clean_headline, clean_body, 6)
        return features

    def other_feature(headline, body):
        features=[]
        features= word_overlap_features(features, headline, body)
        return features
    X = []
    for i, (headline, body) in tqdm(enumerate(zip(headlines, bodies))):
        lst= binary_co_occurence(headline, body) + binary_co_occurence_stops(headline, body) + count_grams(headline, body)+ other_feature(headline, body)
        X.append(lst)


    X =np.array(X)
    return X

In [225]:
#train_handF= hand_features(trainFile['Headline'].tolist(), trainFile['articleBody'].tolist())
#test_handF=hand_features(testFile['Headline'].tolist(), testFile['articleBody'].tolist())
test_handF2=hand_features(testFile2['Title'].tolist(), testFile2['Tweet'].tolist())

18317it [00:19, 925.50it/s] 


In [226]:
from scipy.sparse import  hstack

In [227]:
train_final= hstack([train_head_vec,train_body_vec]).toarray()


In [263]:
train_final

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00537634],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00546448],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.06493506],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.1369863 ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.1369863 ]])

In [228]:
#test_final= hstack([test_head_vec,test_body_vec]).toarray()
test_final2= hstack([test_head_vec2,test_body_vec2]).toarray()

In [229]:
train_final =np.concatenate((train_final,train_handF), axis=1)
#test_final =np.concatenate((test_final,test_handF), axis=1)
test_final2 =np.concatenate((test_final2,test_handF2), axis=1)

In [230]:
#train_final= np.reshape(train_final,(train_final.shape[0],1,train_final.shape[1]))
#test_final2= np.reshape(test_final2,(test_final2.shape[0],1,test_final2.shape[1]))

In [231]:
print(type(train_final), train_final.shape, test_final2.shape)

<class 'numpy.ndarray'> (49972, 187) (18317, 187)


In [232]:
#trainFile.head()

In [233]:
#train_labels= trainFile['Stance'].copy()
#test_labels= testFile['Stance'].copy()

In [234]:
from keras.layers import Input, concatenate,LSTM,Flatten, Dense,Dropout
from keras.models import Model


In [235]:
inp = Input(shape=(train_final.shape[1],))
# lstm = LSTM(150,return_sequences=True)(inp)
lay1= Dense(200, activation= 'tanh')(inp)
lay1= Dense(100, activation= 'sigmoid')(lay1)
# lay1= Dropout(0.3)(lay1)
lay2= Dense(40, activation= 'sigmoid')(lay1)
outp= Dense(4,activation='sigmoid')(lay2)

In [236]:
model= Model(inputs=[inp], outputs=[outp])
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])


In [237]:
# model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])


In [238]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         (None, 187)               0         
_________________________________________________________________
dense_25 (Dense)             (None, 200)               37600     
_________________________________________________________________
dense_26 (Dense)             (None, 100)               20100     
_________________________________________________________________
dense_27 (Dense)             (None, 40)                4040      
_________________________________________________________________
dense_28 (Dense)             (None, 4)                 164       
Total params: 61,904
Trainable params: 61,904
Non-trainable params: 0
_________________________________________________________________


In [239]:
#Y = pd.get_dummies(trainFile['Stance']).values

In [240]:
#Y.shape

In [241]:
#testY = pd.get_dummies(testFile['Stance'] ).values

In [242]:
# Y= np.reshape(Y,(Y.shape[0],1,Y.shape[1]))
# testY= np.reshape(testY,(testY.shape[0],1,testY.shape[1]))

In [243]:
model.fit([train_final],[Y],epochs=5,batch_size=10,verbose=1)

Epoch 1/5
49972/49972 [==============================] - 9s 181us/step - loss: 0.3119 - acc: 0.8842
Epoch 2/5
49972/49972 [==============================] - 8s 166us/step - loss: 0.2677 - acc: 0.9007
Epoch 3/5
49972/49972 [==============================] - 8s 167us/step - loss: 0.2552 - acc: 0.9050
Epoch 4/5
49972/49972 [==============================] - 8s 166us/step - loss: 0.2420 - acc: 0.9088
Epoch 5/5
49972/49972 [==============================] - 8s 170us/step - loss: 0.2304 - acc: 0.9126


In [244]:
train_final

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00537634],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00546448],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.06493506],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.1369863 ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.1369863 ]])

In [245]:
test_final2

array([[0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.22222222],
       [0.        , 0.        , 0.        , ..., 4.        , 4.        ,
        0.5       ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.08      ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.13333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.13333333]])

In [246]:
prediction= model.predict([test_final2],verbose=1)


18317/18317 [==============================] - 1s 38us/step


In [247]:
prediction[0]

array([0.535216  , 0.19903153, 0.2712276 , 0.00082791], dtype=float32)

In [248]:
#scor, acc = model.evaluate([test_final],[testY])

In [249]:
#test_final

In [250]:
#acc

In [251]:
cls= prediction.argmax(axis=-1)

In [252]:
np.unique(cls), cls.shape, type(cls[0])

(array([0, 1, 2, 3]), (18317,), numpy.int64)

In [253]:
#trainFile['Stance'].value_counts()

In [254]:
# np.unique(cls)
acls=[]
for i in range(len(cls)):
    if cls[i]== 0:
        acls.append("agree")
    elif cls[i]== 1:
        acls.append("disagree")
    elif cls[i]== 2:
        acls.append("discuss")
    elif cls[i]== 3:
        acls.append("unrelated")

In [255]:
len(acls)

18317

In [256]:
len(acls)

18317

In [257]:
len(testFile2)

18317

In [258]:
testFile2['labels'] = acls

In [259]:
testFile2.labels.unique()

array(['agree', 'discuss', 'unrelated', 'disagree'], dtype=object)

In [260]:
testFile2.head()

Claim   ...      labels
6       0   ...       agree
14      0   ...     discuss
17      0   ...       agree
18      0   ...       agree
20      0   ...       agree

[5 rows x 6 columns]

In [261]:
testFile2.to_excel('GF_ST_NN.xlsx',index=False)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
import matplotlib.pyplot as plt

In [ ]:
train_labels= trainFile['Stance'].copy()
test_labels= testFile['Stance'][:]

In [ ]:
testFile

In [ ]:
matrix1 = confusion_matrix(test_labels, acls)

In [ ]:
matrix1

In [ ]:
def plot_confusion_matrix(cm,
                          target_names,
                          title='Confusion matrix',
                          cmap=None,
                          normalize=True):
    """
    given a sklearn confusion matrix (cm), make a nice plot

    Arguments
    ---------
    cm:           confusion matrix from sklearn.metrics.confusion_matrix

    target_names: given classification classes such as [0, 1, 2]
                  the class names, for example: ['high', 'medium', 'low']

    title:        the text to display at the top of the matrix

    cmap:         the gradient of the values displayed from matplotlib.pyplot.cm
                  see http://matplotlib.org/examples/color/colormaps_reference.html
                  plt.get_cmap('jet') or plt.cm.Blues

    normalize:    If False, plot the raw numbers
                  If True, plot the proportions

    Usage
    -----
    plot_confusion_matrix(cm           = cm,                  # confusion matrix created by
                                                              # sklearn.metrics.confusion_matrix
                          normalize    = True,                # show proportions
                          target_names = y_labels_vals,       # list of names of the classes
                          title        = best_estimator_name) # title of graph

    Citiation
    ---------
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html

    """
    import matplotlib.pyplot as plt
    import numpy as np
    import itertools

    accuracy = np.trace(cm) / float(np.sum(cm))
    misclass = 1 - accuracy

    if cmap is None:
        cmap = plt.get_cmap('Blues')

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()

    if target_names is not None:
        tick_marks = np.arange(len(target_names))
        plt.xticks(tick_marks, target_names, rotation=45)
        plt.yticks(tick_marks, target_names)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]


    thresh = cm.max() / 1.5 if normalize else cm.max() / 2
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        if normalize:
            plt.text(j, i, "{:0.4f}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")
        else:
            plt.text(j, i, "{:,}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")


    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label\naccuracy={:0.4f}; misclass={:0.4f}'.format(accuracy, misclass))
    plt.show()

In [ ]:
plot_confusion_matrix(cm=matrix1,target_names=['agree', 'disagree', 'discuss', 'unrelated'])

In [ ]:
trainFile['Stance']

In [ ]:
trainFile['Stance'].value_counts()

In [ ]:
testFile['Stance'].value_counts()